main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('logout', views.logoutUser, name='logoutUser'),
]

portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('prof/', include('prof.urls')),
    path('student/', include('student.urls')),
]

main/models/group.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User

class Special_Students(models.Model):
    professor = models.ForeignKey(User, limit_choices_to={'groups__name': "Professor"}, on_delete=models.CASCADE)
    category_name = models.CharField(max_length=10)
    students = models.ManyToManyField(User, limit_choices_to={'groups__name': "Student"}, related_name='student_groups')

    def __str__(self):
        return self.category_name


class Group_Form(ModelForm):
    class Meta:
        model = Special_Students
        fields = '__all__'
        exclude = ['professor']

prof/models.py
from django.db import models

# Create your models here.

prof/views/exam.py
from django.shortcuts import render, redirect
from main.models import *
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden

def view_exams(request):
    prof = request.user

    new_Form = ExamForm()
    new_Form.fields["student_group"].queryset = Special_Students.objects.filter(
        professor=prof)
    new_Form.fields["question_paper"].queryset = Question_Paper.objects.filter(
        professor=prof)

    if request.method == 'POST':
        form = ExamForm(request.POST)
        if form.is_valid():
            exam = form.save(commit=False)
            exam.professor = prof
            exam.save()
            form.save_m2m()
            return redirect('prof:view_exams')

    exams = Exam_Model.objects.filter(professor=prof)

    return render(request, 'prof/exam/view_exams.html', {
        'exams': exams, 'examform': new_Form, 'prof': prof,
    })
    

def view_exam(request, exam_id):
    prof = request.user
    exam = Exam_Model.objects.get(professor=prof, pk=exam_id)
    return render(request, 'prof/exam/view_exam.html', {
        'exam': exam, 'prof': prof, 'student_group': exam.student_group.all()
    })
    

def edit_exam(request, exam_id):
    prof = request.user
    exam = Exam_Model.objects.filter(professor=prof, pk=exam_id).first()
    
    new_Form = ExamForm(instance=exam)
    new_Form.fields["student_group"].queryset = Special_Students.objects.filter(professor=prof)
    new_Form.fields["question_paper"].queryset = Question_Paper.objects.filter(professor=prof)

    if request.method == 'POST':
        form = ExamForm(request.POST, instance=exam)
        if form.is_valid():
            form.save()
            return redirect('prof:view_exams')

    return render(request, 'prof/exam/edit_exam.html', {
        'form': new_Form, 'exam': exam, 'prof': prof
    })
    

def delete_exam(request, exam_id):
    prof = request.user
    exam = Exam_Model.objects.get(professor=prof, pk=exam_id)
    exam.delete()
    return redirect('prof:view_exams')

prof/views/group.py
from django.shortcuts import render, redirect
from main.models import *
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden

def create_student_group(request):
    prof = request.user

    if request.method == "POST":
        form = Group_Form(request.POST)
        if form.is_valid():
            group = form.save(commit=False)
            group.professor = prof
            group.save()
            form.save_m2m()
            
            return redirect('prof:view_groups')

    return render(request, 'prof/group/addview_groups.html', {
        'special_students_db': Special_Students.objects.filter(professor=prof), 'prof': prof, 'groupForm': Group_Form()
    })
    

def view_specific_group(request, group_id):
    prof = request.user
    group = Special_Students.objects.get(professor=prof, pk=group_id)

    return render(request, 'prof/group/view_specific_group.html', {
        'group': group, 'prof': prof, 'group_students': group.students.all()
    })
    

def view_student_in_group(request, group_id):
    prof = request.user
    group = Special_Students.objects.get(professor=prof, pk=group_id)

    if request.method == 'POST':
        student_username = request.POST['username']
        student = User.objects.get(username=student_username)
        group.students.add(student)

    return render(request, 'prof/group/view_special_stud.html', {
        'students': group.students.all(), 'group': group, 'prof': prof
    })
    

def edit_group(request, group_id):
    prof = request.user 
    group = Special_Students.objects.get(professor=prof, pk=group_id)
    group_form = Group_Form(instance=group)
    
    if request.method == "POST":
        form = Group_Form(request.POST, instance=group)
        if form.is_valid():
            form.save()
            return redirect('prof:view_groups')

    return render(request, 'prof/group/edit_group.html', {
        'prof':prof, 'group':group, 'group_form': group_form
    })
    

def delete_group(request, group_id):
    prof = request.user
    Special_Students.objects.filter(professor=prof, pk=group_id).delete()
    return redirect('prof:view_groups')
    

prof/templates/prof/group/addview_groups.html
{% extends 'prof/base/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Student Groups{% endblock title %}
{% block navbar_title %}{{ prof.username }}{% endblock navbar_title %}
{% block navitem_title %}Groups{% endblock navitem_title %}

{% block buttons %}
    <a class="btn btn-light" href="{% url 'prof:index' %}">Home</a> 
{% endblock buttons %}

{% block body %}
    <div class="container-fluid">
        <h3 class="alert alert-secondary my-1" align="center">Create a new group</h3>
        <div align='center' id="create_group">
            <div class="container d-flex h-100 row justify-content-center col-20">
                <form style="width: 80%; font-weight: bolder;"  method="POST">
                    {% csrf_token %}
                    {{ groupForm|crispy }}
                    <input class="btn btn-success" type="submit" value="Create">
                </form>
            </div>
        </div>
        <div id='groups'>
            <h1 class="alert alert-info my-3" align="center">Groups</h1>
            <form class="form-inline my-2 my-lg-0">
                <input id="searchGroup" class="form-control mr-sm-2" type="search" placeholder="Search Group"
                    aria-label="Search">
                    <a class="btn btn-dark" href="{% url 'prof:view_exams' %}" target="_blank">View Exams</a>
            </form>
            <div class="row">
                {% for group in special_students_db %}
                <div class="card my-3 mx-5 col-sm-3">
                    <h3 class="card-header">{{ group.category_name }}</h3>
                    <div class="card-body">
                        <p class="card-text">
                            <h4 class="card-subtitle mb-2 text-muted">Students</h4>
                            {% for stud in group.students.all %}
                            {{stud.username}}
                            {% endfor %}
                            <br><br>
                            <h4 class="card-subtitle mb-2 text-muted">Exams</h4>
                            {% for exam in group.exams.all %}
                                {{ exam.name }}
                                {% empty %}
                                    No exams associated
                            {% endfor %}
                        </p>
                        <a href="{% url 'prof:edit_group' group.id %}"
                            class="card-link btn btn-info">Edit</a>
                    </div>
                </div>
                {% empty %}
                <h3>No groups</h3>
                {% endfor %}
            </div>
        </div>
    </div>
    <script src="{% static 'prof/js/groups.js' %}"></script>
{% endblock body %}

prof/templates/prof/group/edit_group.html
{% extends 'prof/base/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Edit group{% endblock title %}
{% block navbar_title %}Edit group{% endblock navbar_title %}

{% block buttons %}
    <a class="btn btn-warning" href="{% url 'prof:view_groups' %}">Cancel</a>
{% endblock buttons %}

{% block body %}
    <div align='center' class="container-fluid">
        <div class="container d-flex h-100 row justify-content-center col-50">
            <form align="center" method="POST">
                {% csrf_token %}
                {{ group_form|crispy }}
                <input class="btn btn-info" type="submit" value="Update">
            </form>
        </div>
        <a onclick="return confirm('Are you sure you want to delete this group?')" class="btn btn-danger my-3" href="{% url 'prof:delete_group' group.id %}">Delete</a><br>
    </div>
{% endblock body %}

prof/templates/prof/group/view_special_stud.html
{% extends 'prof/base/base.html' %}

{% block title %}Students in group{% endblock title %}
{% block navbar_title %}Group: {{ group.category_name}}{% endblock navbar_title %}

{% block body %}
    <div class="container-fluid">
        <div>
            <h2>Add Student to group</h2>
            <form method="POST">
                {% csrf_token %}
                <h4>Username</h4>
                <input type="text" placeholder="Username" name="username">
                <input type="submit" value="Add">
            </form>
        </div>

        <div>
            <h3>Students:</h3><br>
            <ul>
                {% for student in students %}
                <li>{{student.username}}</li>
                {% empty %}
                <h4>No students in the group</h4>
                {% endfor %}
            </ul>
        </div>
    </div>


    <a class="btn btn-primary" href="{% url 'prof:view_specific_group' group.id %}">Go back to this group</a>
{% endblock body %}

prof/templates/prof/group/view_specific_group.html
{% extends 'prof/base/base.html' %}

{% block title %}About group{% endblock title %}
{% block navbar_title %}Group: {{ group.category_name }}{% endblock navbar_title %}

{% block buttons %}
    <a class="btn btn-light" href="{% url 'main:logoutUser' %}">Logout</a>
{% endblock buttons %}

{% block body %}
    <div class="container-fluid">
        <div align='center' id="group_students">
        <h2>Students in group</h2>
        <ul>
            {% for s in group_students %}
                <li>{{ s.username }}</li>
                {% empty %}
                    <h3>No students added in group</h3>
            {% endfor %}
        </ul>
    </div>
    </div>
    
    <a class="btn btn-primary mx-3 my-3" href="{% url 'prof:edit_group' group.id %}">Edit group</a><br>
    <a class="btn btn-primary mx-3 my-3" href="{% url 'prof:view_groups' %}">Go back to Groups</a>
{% endblock body %}